codebook:
  path: "/gpfs/mindphidata/cdm_repos/github/docs/docs/tables/"
  fname_metadata: "CDM-Codebook - metadata.csv"
  fname_tables: "CDM-Codebook - tables.csv"
  fname_project: "CDM-Codebook - project.csv"

inputs:
  # Credential file
  env_minio: "/gpfs/mindphidata/fongc2/minio_env.txt"
  # Input file of all sample and patient IDs that should be included in the portal
  fname_cbio_sid: "/gpfs/mindphidata/cdm_repos_dev/dev/data/impact-data/mskimpact_heme/data_clinical_sample.txt"
  # Exclusion list (TODO: Consider deprecating since have a to USE list above)
  fname_sample_remove: "/gpfs/mindphidata/cdm_repos/github/cdm-cbioportal-etl/pipeline/mskimpact_clinical_data_remove.tsv"
  # Data manifest files (MinIO)
  fname_manifest_patient: "cbioportal/summary_manifests/mskimpact_heme/summary_manifest_patient.csv"
  fname_manifest_sample: "cbioportal/summary_manifests/mskimpact_heme/summary_manifest_sample.csv"
  # Intermediate summary file and header location on minio
  path_minio_cbio_summary_intermediate: "cbioportal/intermediate_files/mskimpact_heme/"
  # folder path for final deid files
  path_datahub: "/gpfs/mindphidata/cdm_repos_dev/dev/data/cdm-data/mskimpact_heme"
  path_minio_cbio: "cbioportal/mskimpact_heme/"
  # Variable for cBioPortal production or test portal study use
  production_or_test: "production"

inputs_databricks:
  overwrite: True
  fname_databricks_config: "/gpfs/mindphidata/cdm_repos/databricks_env_prod_group.txt"
  catalog: "cdsi_prod"
  schema: "cdsi_data_deid"
  volume: "cdsi_data_deid_volume"
  sep: "\t"

template_files:
  # Header template for patient summary file
  fname_cbio_header_template_p: "cbioportal/cbioportal_summary_header_patient.tsv"
  # Header template for sample summary file
  fname_cbio_header_template_s: "cbioportal/cbioportal_summary_header_sample.tsv"
  # Patient ID list in the cbioportal format. Additional patient summary information is appended to this. Derived from `inputs.fname_cbio_sid`
  fname_p_sum_template_cdsi: "cbioportal/intermediate_files/mskimpact_heme/data_clinical_patient_template_cdsi.txt"
  # Sample ID list in the cbioportal format. Additional patient summary information is appended to this. Derived from `inputs.fname_cbio_sid`
  fname_s_sum_template_cdsi: "cbioportal/intermediate_files/mskimpact_heme/data_clinical_sample_template_cdsi.txt"

# TODO all tables on minio should be in codebook
#phi_generated_files:
#  fname_follow_up_table: "demographics/table_timeline_follow_up.tsv"

# File names
deid_filenames:
  summary_patient: "data_clinical_patient.txt"
  summary_sample: "data_clinical_sample.txt"

